### ISSUE TITLE
Mazel-Tovr / Mazel-Tovr

### ISSUE THREAD

**Issue by egor-zavgorodnev** [Mazel-Tovr/Mazel-Tovr#1]
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr
Mazel-Tovr

**Comment by Mazel-Tovr** [comment]
how to ban some one on gh ?

**Comment by egor-zavgorodnev** [comment]
why?
